export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_CONTINENTS = "GET_CONTINENTS";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const CLEAR_COUNTRY_DETAIL = "CLEAR_COUNTRY_DETAIL";
export const SET_ACTIVITIES = "SET_ACTIVITIES";
export const FILTER_BY_CONTINENTS = "FILTER_BY_CONTINENTS";
export const SORT_COUNTRIES = "SORT_COUNTRIES";